source "https://rubygems.org"

gem "middleman", "~> 3.3.7"
gem "middleman-blog", "~> 3.5.3"
gem "middleman-syntax", "~> 2.0.0"
gem "middleman-minify-html", "~> 3.1.1"
gem "redcarpet", "~> 3.1.1"
gem "nokogiri", "~> 1.6.1"
gem "slim", "~> 3.0.1"
gem "builder", "~> 3.2.2"
