source "https://rubygems.org"

gem "middleman", "~> 3.2.2"
gem "middleman-blog", "~> 3.5.2"
gem "middleman-syntax", "~> 2.0.0"
gem "middleman-minify-html", "~> 3.1.1"
gem "redcarpet", "~> 3.1.1"
gem "nokogiri", "~> 1.6.1"
gem "rb-inotify", "~> 0.9"
gem "slim", "~> 2.0.2"
gem "rouge", github: "mekishizufu/rouge", ref: "d98b3a5"
gem "builder", "~> 3.2.2"
